#!/usr/bin/env bun
/**
 * Migrate legacy Django SQLite data into D1 + R2.
 *
 * Source:  ../db.sqlite3::api_interaction  (222 rows of real data)
 * Output:  migrations/seed.sql  +  R2 objects uploaded via wrangler
 *
 * Usage:
 *   bun run scripts/migrate.ts              # hits production D1/R2
 *   bun run scripts/migrate.ts --local      # hits local wrangler simulator
 *   bun run scripts/migrate.ts --sql-only   # just regenerate seed.sql, skip R2 uploads
 *   bun run scripts/migrate.ts --skip-existing  # skip R2 uploads for keys already present
 */

import { Database } from "bun:sqlite";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKER_ROOT = resolve(__dirname, "..");
const REPO_ROOT = resolve(WORKER_ROOT, "..");

const args = new Set(process.argv.slice(2));
const LOCAL = args.has("--local");
const SQL_ONLY = args.has("--sql-only");
const SKIP_EXISTING = args.has("--skip-existing");

const DB_PATH = process.env.SRC_DB ?? resolve(REPO_ROOT, "db.sqlite3");
const MEDIA_ROOT = process.env.SRC_MEDIA ?? resolve(REPO_ROOT, "media");
const BUCKET = process.env.R2_BUCKET ?? "museum-media";
// wrangler d1 needs --remote explicitly; r2 defaults to remote (only --local opts out)
const D1_REMOTE_FLAG = LOCAL ? "--local" : "--remote";
const R2_LOCAL_FLAG = LOCAL ? ["--local"] : [];

type Row = {
  id: string;
  response: string;
  image: string;
  date: string;
};

function normalizeId(id: string): string {
  const s = id.replace(/-/g, "").toLowerCase();
  if (s.length === 32 && /^[0-9a-f]{32}$/.test(s)) {
    return `${s.slice(0, 8)}-${s.slice(8, 12)}-${s.slice(12, 16)}-${s.slice(
      16,
      20,
    )}-${s.slice(20)}`;
  }
  return id;
}

function normalizeDate(d: string): string {
  if (!d) return new Date().toISOString();
  // Django stores "YYYY-MM-DD HH:MM:SS.ffffff" (naive — treat as UTC)
  const t = Date.parse(d.includes("T") ? d : d.replace(" ", "T") + "Z");
  if (!Number.isNaN(t)) return new Date(t).toISOString();
  return d;
}

function sqlQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

async function r2KeyExists(key: string): Promise<boolean> {
  const r = spawnSync(
    "wrangler",
    ["r2", "object", "get", `${BUCKET}/${key}`, "--pipe", ...R2_LOCAL_FLAG],
    { stdio: ["ignore", "ignore", "ignore"] },
  );
  return r.status === 0;
}

function uploadToR2(key: string, file: string): boolean {
  const r = spawnSync(
    "wrangler",
    ["r2", "object", "put", `${BUCKET}/${key}`, "--file", file, ...R2_LOCAL_FLAG],
    { stdio: "inherit" },
  );
  return r.status === 0;
}

// ───────────────────────────── main ─────────────────────────────

if (!existsSync(DB_PATH)) {
  console.error(`✗ Source database not found: ${DB_PATH}`);
  console.error(`  Override with env SRC_DB=/path/to/db.sqlite3`);
  process.exit(1);
}

console.log(`→ Reading ${DB_PATH}`);
const db = new Database(DB_PATH, { readonly: true });
const rows = db
  .query<Row, []>(
    "SELECT id, response, image, date FROM api_interaction ORDER BY date ASC",
  )
  .all();
console.log(`  found ${rows.length} rows`);

// 1. Emit seed SQL
const migrationsDir = join(WORKER_ROOT, "migrations");
mkdirSync(migrationsDir, { recursive: true });
const lines: string[] = [];
lines.push("-- Auto-generated by scripts/migrate.ts");
lines.push("-- Source: Django api_interaction → D1 interactions");
lines.push("");

// D1 forbids explicit BEGIN/COMMIT — Durable Objects manage transactions.
for (const r of rows) {
  const id = normalizeId(r.id);
  const date = normalizeDate(r.date);
  const response = r.response ?? "";
  const image = r.image;
  lines.push(
    `INSERT OR IGNORE INTO interactions (id, response, image, date) VALUES (${sqlQuote(
      id,
    )}, ${sqlQuote(response)}, ${sqlQuote(image)}, ${sqlQuote(date)});`,
  );
}
const seedFile = join(migrationsDir, "seed.sql");
writeFileSync(seedFile, lines.join("\n"));
console.log(`✓ Wrote ${seedFile} (${rows.length} rows)`);

if (SQL_ONLY) {
  console.log("→ --sql-only: skipping R2 uploads");
  summarize(rows.length, 0, 0, 0);
  process.exit(0);
}

// 2. Upload images to R2
console.log(`→ Uploading images to R2 bucket "${BUCKET}" (${LOCAL ? "local" : "remote"})`);
let uploaded = 0,
  skipped = 0,
  missing = 0,
  failed = 0;

for (let i = 0; i < rows.length; i++) {
  const r = rows[i];
  const key = r.image;
  const src = resolve(MEDIA_ROOT, key);
  const progress = `[${i + 1}/${rows.length}]`;

  if (!existsSync(src)) {
    console.warn(`${progress} ✗ missing file: ${src}`);
    missing++;
    continue;
  }

  if (SKIP_EXISTING && (await r2KeyExists(key))) {
    console.log(`${progress} ↷ skip (exists): ${key}`);
    skipped++;
    continue;
  }

  console.log(`${progress} ↑ ${key}`);
  if (uploadToR2(key, src)) {
    uploaded++;
  } else {
    failed++;
    console.error(`${progress} ✗ upload failed: ${key}`);
  }
}

summarize(rows.length, uploaded, skipped + missing, failed);

console.log("");
console.log("Next steps:");
console.log(`  1. wrangler d1 execute museum-db --file=migrations/0001_init.sql ${D1_REMOTE_FLAG}`);
console.log(`  2. wrangler d1 execute museum-db --file=migrations/seed.sql ${D1_REMOTE_FLAG}`);
if (LOCAL) {
  console.log(`  3. wrangler dev                 # test locally`);
} else {
  console.log(`  3. wrangler deploy              # push Worker to edge`);
}

function summarize(total: number, up: number, skipMissing: number, fail: number) {
  console.log("");
  console.log(`Summary: ${total} rows · uploaded ${up} · skipped/missing ${skipMissing} · failed ${fail}`);
}
