# Generated by Django 5.1.2 on 2024-10-10 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='question',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
